Make the Ballerina project to adhere with VSCode tooling features
ballerina-platform/module-ballerina-jballerina.java.arrays pull request #263
Opened 2021-09-09 04:30 UTC by BuddhiWathsala

## Purpose
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/1746

## Examples

## Checklist
- [x] Linked to an issue
- [ ] Updated the changelog
- [ ] Added tests

2021-09-09 04:37 UTC, daneshk approved these changes

2021-09-09 05:07 UTC, ThisaruGuruge approved these changes

2021-09-09 11:59 UTC, ThisaruGuruge requested changes
Let's do the suggestions done after this PR was sent.

2021-09-10 11:35 UTC, ThisaruGuruge approved these changes

2021-09-10 11:36 UTC, merged